#include <benchmark/benchmark.h>
#include <algorithm>
#include <vector>
#include <immintrin.h>
#include <numeric>
#include <execution>
#include <random>
#include <iostream>

#include <experimental/simd>
namespace stdx = std::experimental;

int64_t findMax_std(std::vector<int64_t>& arr)
{
    /*
    std::max_element is notoriously difficult for a compiler's auto-vectorizer to optimize because of its strict behavior contract.

    It returns an iterator, not a value: The function cannot just find the highest number; it must return a pointer/iterator to the memory location of that number.

    The "First Occurrence" rule: The C++ standard mandates that if the maximum value appears multiple times in the array, std::max_element must return the first occurrence.

    To turn that into SIMD code, the compiler cannot just do a simple vertical vector comparison. It has to maintain a second vector register tracking the memory indices of those elements. When it finds a new maximum, it has to safely update the index register. If there is a tie between vector lanes, it has to execute masking math to ensure the lower index wins.

    When GCC 16's auto-vectorizer encounters the template layers generated by std::execution::unseq, it looks at that index-tracking and tie-breaking logic and almost always flags it as not vectorized: complex control flow or not vectorized: data dependency. It gives up and falls back to a standard sequential loop.
    */
    return *max_element(std::execution::unseq, arr.begin(), arr.end());
}

int64_t findMax_reduce(const std::vector<int64_t>& arr)
{
    /*
    You might wonder: If I told the algorithm to run sequentially (seq), why didn't it drop back down to the slow 477 ns scalar baseline?

    It didn't drop down because you didn't explicitly block vectorization on this new function. More importantly, std::reduce is mathematically allowed to cheat.

    Unlike std::accumulate (which strictly requires a left-to-right processing order), the C++ standard explicitly states that std::reduce is allowed to rearrange the order of operations however it sees fit, even when running sequentially.

    Because GCC 16 sees that the sequential order doesn't matter, its global loop optimizer says: "Excellent, I can auto-vectorize this loop entirely on my own terms."
    */
    return std::reduce(std::execution::unseq, arr.begin(), arr.end(), arr[0],
        [](int64_t a, int64_t b) {
            return std::max(a, b);
        });
}

__attribute__((target("avx512f,avx512vl")))
int64_t findMax_intrinsics(std::vector<int64_t>& arr)
{
    // Assume: size is a multiple of 8
    const std::size_t stride = 8;
    const std::size_t arrSize = arr.size();
    const int64_t* data = arr.data();
    __m512i vmax = _mm512_loadu_si512((__m512i*)data); // first 8 elements

    for (std::size_t i = stride; i < arrSize; i += stride) {
        __m512i v = _mm512_loadu_si512((__m512i*)(data + i));
        vmax = _mm512_max_epi64(vmax, v); // pairwise max of 8 lanes
    }

    // Horizontal reduction: collapse 8 lanes into 1
    // Step 1: split high and low halves
    __m256i lo256 = _mm512_castsi512_si256(vmax);
    __m256i hi256 = _mm512_extracti64x4_epi64(vmax, 1);
    __m256i max256 = _mm256_max_epi64(lo256, hi256);

    // Step 2: reduce 256-bit -> 128-bit
    __m128i lo128 = _mm256_castsi256_si128(max256);
    __m128i hi128 = _mm256_extracti128_si256(max256, 1);
    __m128i max128 = _mm_max_epi64(lo128, hi128);

    // Step 3: reduce 128-bit -> 64-bit
    __m128i hi64 = _mm_unpackhi_epi64(max128, max128);
    __m128i max64 = _mm_max_epi64(max128, hi64);

    return _mm_cvtsi128_si64(max64);
}

__attribute__((target("avx512f,avx512vl")))
int64_t findMax_intrinsics_unrolled(std::vector<int64_t>& arr)
{
    const std::size_t stride = 8;
    const std::size_t unroll = 4;
    const std::size_t totalStride = stride * unroll;
    const std::size_t arrSize = arr.size();
    const int64_t* data = arr.data();

    if (arrSize < totalStride) return findMax_intrinsics(arr);

    __m512i vmax0 = _mm512_loadu_si512((__m512i*)data);
    __m512i vmax1 = _mm512_loadu_si512((__m512i*)(data + stride));
    __m512i vmax2 = _mm512_loadu_si512((__m512i*)(data + 2 * stride));
    __m512i vmax3 = _mm512_loadu_si512((__m512i*)(data + 3 * stride));

    std::size_t i = totalStride;
    for (; i + totalStride <= arrSize; i += totalStride) {
        __m512i v0 = _mm512_loadu_si512((__m512i*)(data + i));
        __m512i v1 = _mm512_loadu_si512((__m512i*)(data + i + stride));
        __m512i v2 = _mm512_loadu_si512((__m512i*)(data + i + 2 * stride));
        __m512i v3 = _mm512_loadu_si512((__m512i*)(data + i + 3 * stride));
        vmax0 = _mm512_max_epi64(vmax0, v0);
        vmax1 = _mm512_max_epi64(vmax1, v1);
        vmax2 = _mm512_max_epi64(vmax2, v2);
        vmax3 = _mm512_max_epi64(vmax3, v3);
    }

    __m512i vmax = _mm512_max_epi64(_mm512_max_epi64(vmax0, vmax1), _mm512_max_epi64(vmax2, vmax3));

    for (; i + stride <= arrSize; i += stride) {
        __m512i v = _mm512_loadu_si512((__m512i*)(data + i));
        vmax = _mm512_max_epi64(vmax, v);
    }

    __m256i lo256 = _mm512_castsi512_si256(vmax);
    __m256i hi256 = _mm512_extracti64x4_epi64(vmax, 1);
    __m256i max256 = _mm256_max_epi64(lo256, hi256);
    __m128i lo128 = _mm256_castsi256_si128(max256);
    __m128i hi128 = _mm256_extracti128_si256(max256, 1);
    __m128i max128 = _mm_max_epi64(lo128, hi128);
    __m128i hi64 = _mm_unpackhi_epi64(max128, max128);
    __m128i max64 = _mm_max_epi64(max128, hi64);

    int64_t result = _mm_cvtsi128_si64(max64);
    for (; i < arrSize; ++i) {
        if (data[i] > result) result = data[i];
    }
    return result;
}

inline __attribute__((always_inline))
int64_t findMaxShared(std::vector<int64_t>& arr)
{
    int64_t max = arr[0];

    for (int64_t v : arr) {
        if (max < v)
            max = v;
    }
    return max;
}

__attribute__((target("avx512f")))
int64_t findMaxAvx512(std::vector<int64_t>& arr)
{
    return findMaxShared(arr);
}

__attribute__((target("avx2")))
int64_t findMaxAvx2(std::vector<int64_t>& arr)
{
    return findMaxShared(arr);
}

//__attribute__((target("arch=x86-64,no-sse,no-avx")))
__attribute__((optimize("no-tree-vectorize", "no-unroll-loops")))
int64_t findMaxScalar(std::vector<int64_t>& arr)
{
    int64_t* pArr = arr.data();
    size_t arrSize = arr.size();
    int64_t max = pArr[0];

    for (size_t i = 0; i < arrSize; ++i) {
        if (max < pArr[i])
            max = pArr[i];
    }
    return max;
}

__attribute__((optimize("no-tree-vectorize", "no-unroll-loops")))
int64_t findMaxScalar_unrolled(std::vector<int64_t>& arr)
{
    int64_t* pArr = arr.data();
    size_t arrSize = arr.size();
    if (arrSize == 0) return 0;

    int64_t max0 = pArr[0];
    int64_t max1 = pArr[0];
    int64_t max2 = pArr[0];
    int64_t max3 = pArr[0];

    size_t i = 0;
    for (; i + 4 <= arrSize; i += 4) {
        if (pArr[i] > max0) max0 = pArr[i];
        if (pArr[i + 1] > max1) max1 = pArr[i + 1];
        if (pArr[i + 2] > max2) max2 = pArr[i + 2];
        if (pArr[i + 3] > max3) max3 = pArr[i + 3];
    }

    int64_t max = std::max({max0, max1, max2, max3});
    for (; i < arrSize; ++i) {
        if (pArr[i] > max) max = pArr[i];
    }
    return max;
}

int64_t findMax_simd_portable(const std::vector<int64_t>& arr)
{
    // Automatically picks the best SIMD width for the target architecture
    using simd_t = stdx::native_simd<int64_t>;
    constexpr size_t width = simd_t::size();

    size_t i = 0;
    simd_t max_v(arr[0]); // Broadcast the first element across all vector lanes

    // Main vector accumulation loop
    for (; i + width <= arr.size(); i += width) {
        simd_t chunk;
        chunk.copy_from(&arr[i], stdx::element_aligned);
        max_v = stdx::max(max_v, chunk); // Element-wise vertical maximum
    }

    // Horizontal reduction down to a single scalar value
    int64_t max_val = stdx::hmax(max_v);

    // Scalar cleanup loop for any remaining trailing elements
    for (; i < arr.size(); ++i) {
        max_val = std::max(max_val, arr[i]);
    }

    return max_val;
}

int64_t findMax_simd_portable_unrolled(const std::vector<int64_t>& arr)
{
    using simd_t = stdx::native_simd<int64_t>;
    constexpr size_t width = simd_t::size();
    constexpr size_t unroll = 4;
    const size_t totalWidth = width * unroll;

    size_t i = 0;
    simd_t max_v0(arr[0]);
    simd_t max_v1(arr[0]);
    simd_t max_v2(arr[0]);
    simd_t max_v3(arr[0]);

    for (; i + totalWidth <= arr.size(); i += totalWidth) {
        simd_t c0, c1, c2, c3;
        c0.copy_from(&arr[i], stdx::element_aligned);
        c1.copy_from(&arr[i + width], stdx::element_aligned);
        c2.copy_from(&arr[i + 2 * width], stdx::element_aligned);
        c3.copy_from(&arr[i + 3 * width], stdx::element_aligned);
        max_v0 = stdx::max(max_v0, c0);
        max_v1 = stdx::max(max_v1, c1);
        max_v2 = stdx::max(max_v2, c2);
        max_v3 = stdx::max(max_v3, c3);
    }

    simd_t max_v = stdx::max(stdx::max(max_v0, max_v1), stdx::max(max_v2, max_v3));

    for (; i + width <= arr.size(); i += width) {
        simd_t chunk;
        chunk.copy_from(&arr[i], stdx::element_aligned);
        max_v = stdx::max(max_v, chunk);
    }

    int64_t max_val = stdx::hmax(max_v);

    for (; i < arr.size(); ++i) {
        max_val = std::max(max_val, arr[i]);
    }

    return max_val;
}

int64_t findMax_simd_avx512(const std::vector<int64_t>& arr)
{
    // Force exactly 8 lanes to map directly to an AVX-512 ZMM register
    using simd_t = stdx::fixed_size_simd<int64_t, 8>;
    using mask_t = typename simd_t::mask_type;
    constexpr size_t width = simd_t::size();

    size_t i = 0;
    simd_t max_v(arr[0]);

    // Main bulk loop (processes chunks of 8 elements)
    for (; i + width <= arr.size(); i += width) {
        simd_t chunk;
        chunk.copy_from(&arr[i], stdx::element_aligned);
        max_v = stdx::max(max_v, chunk);
    }

    // Advanced AVX-512 Optimization: Clean up the tail using hardware masking
    if (i < arr.size()) {
        size_t remainder = arr.size() - i;

        // 1. Generate an index vector: [0, 1, 2, 3, 4, 5, 6, 7]
        simd_t indices([](size_t idx) { return static_cast<int64_t>(idx); });

        // 2. Create the mask by comparing the indices to the remaining size
        mask_t tail_mask = indices < static_cast<int64_t>(remainder);

        // Initialize a dummy vector with the lowest possible values 
        simd_t chunk(std::numeric_limits<int64_t>::lowest());

        // Conditionally load the final partial elements into the active lanes
        stdx::where(tail_mask, chunk).copy_from(&arr[i], stdx::element_aligned);

        // One final vertical max comparison
        max_v = stdx::max(max_v, chunk);
    }

    // Final horizontal reduction
    return stdx::hmax(max_v);
}

int64_t findMax_simd_avx512_unrolled(const std::vector<int64_t>& arr)
{
    using simd_t = stdx::fixed_size_simd<int64_t, 8>;
    using mask_t = typename simd_t::mask_type;
    constexpr size_t width = simd_t::size();
    constexpr size_t unroll = 4;
    const size_t totalWidth = width * unroll;

    size_t i = 0;
    simd_t max_v0(arr[0]);
    simd_t max_v1(arr[0]);
    simd_t max_v2(arr[0]);
    simd_t max_v3(arr[0]);

    for (; i + totalWidth <= arr.size(); i += totalWidth) {
        simd_t c0, c1, c2, c3;
        c0.copy_from(&arr[i], stdx::element_aligned);
        c1.copy_from(&arr[i + width], stdx::element_aligned);
        c2.copy_from(&arr[i + 2 * width], stdx::element_aligned);
        c3.copy_from(&arr[i + 3 * width], stdx::element_aligned);
        max_v0 = stdx::max(max_v0, c0);
        max_v1 = stdx::max(max_v1, c1);
        max_v2 = stdx::max(max_v2, c2);
        max_v3 = stdx::max(max_v3, c3);
    }

    simd_t max_v = stdx::max(stdx::max(max_v0, max_v1), stdx::max(max_v2, max_v3));

    for (; i + width <= arr.size(); i += width) {
        simd_t chunk;
        chunk.copy_from(&arr[i], stdx::element_aligned);
        max_v = stdx::max(max_v, chunk);
    }

    if (i < arr.size()) {
        size_t remainder = arr.size() - i;
        simd_t indices([](size_t idx) { return static_cast<int64_t>(idx); });
        mask_t tail_mask = indices < static_cast<int64_t>(remainder);
        simd_t chunk(std::numeric_limits<int64_t>::lowest());
        stdx::where(tail_mask, chunk).copy_from(&arr[i], stdx::element_aligned);
        max_v = stdx::max(max_v, chunk);
    }

    return stdx::hmax(max_v);
}

constexpr int dataSize = 1024;

std::vector<int64_t> genData(size_t size)
{
    std::cout << "generating data...\n";
    std::vector<int64_t> d;
    d.resize(size);
    std::iota(d.begin(), d.end(), (size / 2) * -1);
    std::shuffle(d.begin(), d.end(), std::mt19937{std::random_device{}()});
    std::cout << "data vector size: " << d.size() << "\n";
    std::cout << "data elements: " << d[0] << ", " << d[1] << ", "
        << d[2] << ", ..., " << d[dataSize - 1] << "\n";
    return d;
}

std::vector<int64_t> data = genData(dataSize);

static void BM_findMax_std(benchmark::State& state)
{
    // std::cout << "findMax_std(data) = " << findMax_std(data) << "\n";
    for (auto _ : state) {
        benchmark::DoNotOptimize(findMax_std(data));
    }
}
BENCHMARK(BM_findMax_std);

static void BM_findMax_reduce(benchmark::State& state)
{
    // std::cout << "findMax_reduce(data) = " << findMax_reduce(data) << "\n";
    for (auto _ : state) {
        benchmark::DoNotOptimize(findMax_reduce(data));
    }
}
BENCHMARK(BM_findMax_reduce);

static void BM_findMax_intrinsics(benchmark::State& state)
{
    // std::cout << "findMax_intrinsics(data) = {}" << findMax_intrinsics(data) << "\n";
    for (auto _ : state) {
        benchmark::DoNotOptimize(findMax_intrinsics(data));
    }
}
//BENCHMARK(BM_findMax_intrinsics);

static void BM_findMax_intrinsics_unrolled(benchmark::State& state)
{
    for (auto _ : state) {
        benchmark::DoNotOptimize(findMax_intrinsics_unrolled(data));
    }
}
//BENCHMARK(BM_findMax_intrinsics_unrolled);

static void BM_findMaxAvx512(benchmark::State& state)
{
    // std::cout << "findMaxAvx512(data) = " << findMaxAvx512(data) << "\n";
    for (auto _ : state) {
        benchmark::DoNotOptimize(findMaxAvx512(data));
    }
}
//BENCHMARK(BM_findMaxAvx512);

static void BM_findMaxAvx2(benchmark::State& state)
{
    // std::cout << "findMaxAvx2(data) = " << findMaxAvx2(data) << "\n";
    for (auto _ : state) {
        benchmark::DoNotOptimize(findMaxAvx2(data));
    }
}
BENCHMARK(BM_findMaxAvx2);

static void BM_findMaxScalar(benchmark::State& state)
{
    // std::cout << "findMaxScalar(data) = " << findMaxScalar(data) << "\n";
    for (auto _ : state) {
        benchmark::DoNotOptimize(findMaxScalar(data));
    }
}
BENCHMARK(BM_findMaxScalar);

static void BM_findMaxScalar_unrolled(benchmark::State& state)
{
    for (auto _ : state) {
        benchmark::DoNotOptimize(findMaxScalar_unrolled(data));
    }
}
BENCHMARK(BM_findMaxScalar_unrolled);

static void BM_findMax_simd_portable(benchmark::State& state)
{
    // std::cout << "findMax_simd_portable(data) = " << findMax_simd_portable(data) << "\n";
    for (auto _ : state) {
        benchmark::DoNotOptimize(findMax_simd_portable(data));
    }
}
BENCHMARK(BM_findMax_simd_portable);

static void BM_findMax_simd_portable_unrolled(benchmark::State& state)
{
    for (auto _ : state) {
        benchmark::DoNotOptimize(findMax_simd_portable_unrolled(data));
    }
}
BENCHMARK(BM_findMax_simd_portable_unrolled);

static void BM_findMax_simd_avx512(benchmark::State& state)
{
    // std::cout << "findMax_simd_avx512(data) = " << findMax_simd_avx512(data) << "\n";
    for (auto _ : state) {
        benchmark::DoNotOptimize(findMax_simd_avx512(data));
    }
}
BENCHMARK(BM_findMax_simd_avx512);

static void BM_findMax_simd_avx512_unrolled(benchmark::State& state)
{
    for (auto _ : state) {
        benchmark::DoNotOptimize(findMax_simd_avx512_unrolled(data));
    }
}
BENCHMARK(BM_findMax_simd_avx512_unrolled);

BENCHMARK_MAIN();
